language: python
sudo: false
env:
  - ENABLE_LIBSPHINXAD=1
addons:
  apt:
    packages:
      - swig
      - libpulse-dev
python:
  - '2.7'
  - '3.2'
  - '3.3'
  - '3.4'
  - '3.5'
script:
  - python setup.py test
